/**
 * This class represents a rectangle.
 * Getters and setters are automatically generated by Kotlin.
 * To use a property, we simply refer to it by name, as if it were a field in Java.
 */
open class Rectangle(open var width: Int, open var height: Int){
}